sudo: required
language: python
python:
  - "3.6"
before_install:
    - pip install -r requirements.txt -t src/build/
    - cp src/*.py src/build/
script:
    - aws cloudformation package --template-file template.yaml --s3-bucket sam-template-packaged --output-template-file output.yaml
    - aws cloudformation deploy --template-file output.yaml --stack-name watson --capabilities CAPABILITY_IAM
